/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ListPagination {
        /**
          * The count of all items in the list.
         */
        "count": number;
        /**
          * How much items per page shall be shown in the list?
         */
        "itemsPerPage": number;
        /**
          * The current offset of the list.
         */
        "offset": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PokemonList {
        /**
          * The title of this Pokémon List.
         */
        "listTitle": string;
    }
}
declare global {
    interface HTMLListPaginationElement extends Components.ListPagination, HTMLStencilElement {
    }
    var HTMLListPaginationElement: {
        prototype: HTMLListPaginationElement;
        new (): HTMLListPaginationElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPokemonListElement extends Components.PokemonList, HTMLStencilElement {
    }
    var HTMLPokemonListElement: {
        prototype: HTMLPokemonListElement;
        new (): HTMLPokemonListElement;
    };
    interface HTMLElementTagNameMap {
        "list-pagination": HTMLListPaginationElement;
        "my-component": HTMLMyComponentElement;
        "pokemon-list": HTMLPokemonListElement;
    }
}
declare namespace LocalJSX {
    interface ListPagination {
        /**
          * The count of all items in the list.
         */
        "count"?: number;
        /**
          * How much items per page shall be shown in the list?
         */
        "itemsPerPage"?: number;
        /**
          * The current offset of the list.
         */
        "offset"?: number;
        /**
          * Emits, when a paging is triggered.
         */
        "onPaging"?: (event: CustomEvent<{
            offset: number;
            itemsPerPage: number;
        }>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PokemonList {
        /**
          * The title of this Pokémon List.
         */
        "listTitle"?: string;
    }
    interface IntrinsicElements {
        "list-pagination": ListPagination;
        "my-component": MyComponent;
        "pokemon-list": PokemonList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "list-pagination": LocalJSX.ListPagination & JSXBase.HTMLAttributes<HTMLListPaginationElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pokemon-list": LocalJSX.PokemonList & JSXBase.HTMLAttributes<HTMLPokemonListElement>;
        }
    }
}
